/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DatabaseProcess.ShareData;
import DatabaseProcess.TaiKhoan;
import DatabaseProcess.KhachHang;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Mỹ Nhung
 */
public class DangKyKHFrame extends javax.swing.JFrame {

    private DangNhapFrame login;

    /**
     * Creates new form DangKyKHFrame
     */
    public DangKyKHFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbTenKhachHang = new javax.swing.JLabel();
        lbGioiTinh = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lbDiaChi = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lbSDT = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbCCCD = new javax.swing.JLabel();
        RadioNu = new javax.swing.JRadioButton();
        RadioNam = new javax.swing.JRadioButton();
        lbMaKhachHang = new javax.swing.JLabel();
        txtMaKhachHang = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCCCD = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbMatKhau = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        btnTaoMoi = new javax.swing.JButton();
        btnDangKy = new javax.swing.JButton();
        lbTenTaiKhoan = new javax.swing.JLabel();
        lbXacNhanMatKhau = new javax.swing.JLabel();
        txtXacNhanMatKhau = new javax.swing.JPasswordField();
        lbMaTaiKhoan = new javax.swing.JLabel();
        txtTenTaiKhoan = new javax.swing.JTextField();
        txtMaTaiKhoan = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnTrangDangNhap = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng ký khách hàng");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0,0,0,10
        ));

        jLabel5.setBackground(new java.awt.Color(102, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("THÔNG TIN NGƯỜI DÙNG");

        lbTenKhachHang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTenKhachHang.setText("Họ và tên:");

        lbGioiTinh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbGioiTinh.setText("Giới tính:");

        txtHoTen.setBackground(new java.awt.Color(204, 204, 204));
        txtHoTen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        lbDiaChi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbDiaChi.setText("Địa chỉ:");

        txtSDT.setBackground(new java.awt.Color(204, 204, 204));
        txtSDT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        lbSDT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbSDT.setText("Số điện thoại:");

        lbEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbEmail.setText("Email:");

        lbCCCD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbCCCD.setText("CCCD:");

        RadioNu.setText("Nữ");
        RadioNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioNuActionPerformed(evt);
            }
        });

        RadioNam.setText("Nam");
        RadioNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioNamActionPerformed(evt);
            }
        });

        lbMaKhachHang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbMaKhachHang.setText("Mã khách hàng:");

        txtMaKhachHang.setBackground(new java.awt.Color(204, 204, 204));
        txtMaKhachHang.setEnabled(false);
        txtMaKhachHang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txtDiaChi.setBackground(new java.awt.Color(204, 204, 204));
        txtDiaChi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txtCCCD.setBackground(new java.awt.Color(204, 204, 204));
        txtCCCD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lbMaKhachHang))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lbTenKhachHang))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lbGioiTinh))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(lbDiaChi))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbSDT))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(lbEmail))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(lbCCCD)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(RadioNam)
                                .addGap(56, 56, 56)
                                .addComponent(RadioNu))
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(txtHoTen)
                            .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(txtCCCD, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(txtSDT)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel5)))
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaKhachHang))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbTenKhachHang))
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbGioiTinh))
                    .addComponent(RadioNam)
                    .addComponent(RadioNu))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDiaChi)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbSDT))
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCCCD)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 340, 350));

        jPanel1.setBackground(new java.awt.Color(0,0,0,10));

        jLabel4.setBackground(new java.awt.Color(102, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("THÔNG TIN TÀI KHOẢN");

        lbMatKhau.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbMatKhau.setText("Mật khẩu:");

        txtMatKhau.setBackground(new java.awt.Color(204, 204, 204));

        btnTaoMoi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTaoMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Refresh.png"))); // NOI18N
        btnTaoMoi.setText("Tạo mới");
        btnTaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMoiActionPerformed(evt);
            }
        });

        btnDangKy.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDangKy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/sign-up.png"))); // NOI18N
        btnDangKy.setText("Đăng ký");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });

        lbTenTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTenTaiKhoan.setText("Tên tài khoản:");

        lbXacNhanMatKhau.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbXacNhanMatKhau.setText("Xác nhận mật khẩu:");

        txtXacNhanMatKhau.setBackground(new java.awt.Color(204, 204, 204));

        lbMaTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbMaTaiKhoan.setText("Mã tài khoản:");

        txtTenTaiKhoan.setBackground(new java.awt.Color(204, 204, 204));
        txtTenTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txtMaTaiKhoan.setEnabled(false);
        txtMaTaiKhoan.setBackground(new java.awt.Color(204, 204, 204));
        txtMaTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbTenTaiKhoan)
                                .addComponent(lbMatKhau)
                                .addComponent(lbXacNhanMatKhau))
                            .addGap(18, 18, 18)
                            .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(47, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnDangKy)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtXacNhanMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnTaoMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(46, 46, 46))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbMaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(45, 45, 45)))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenTaiKhoan)
                    .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMatKhau)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbXacNhanMatKhau)
                    .addComponent(txtXacNhanMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangKy)
                    .addComponent(btnTaoMoi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 350, -1));

        jPanel3.setBackground(new java.awt.Color(214, 172, 150));

        jLabel8.setBackground(new java.awt.Color(102, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel8.setText("ĐĂNG KÝ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 80));

        btnTrangDangNhap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTrangDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_back_16px.png"))); // NOI18N
        btnTrangDangNhap.setText("Quay lại trang đăng nhập");
        btnTrangDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrangDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Màn hình đăng nhập.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 760, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoMoiActionPerformed
        // TODO add your handling code here:
        txtHoTen.setText("");
        txtDiaChi.setText("");
        txtEmail.setText("");
        txtCCCD.setText("");
        txtSDT.setText("");
        //gioi tinh
        txtMaTaiKhoan.setText("");
        txtTenTaiKhoan.setText("");
        txtMatKhau.setText("");
        txtXacNhanMatKhau.setText("");
        txtMaTaiKhoan.setText("");
        
    }//GEN-LAST:event_btnTaoMoiActionPerformed

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        // TODO add your handling code here:

        // Xử lý thông tin khách hàng
        String hoTen = txtHoTen.getText();
        String diaChi = txtDiaChi.getText();
        int gioiTinh = 0;
        
        String Email = txtEmail.getText();
        String regex_Email = "^[a-zA-Z][\\\\w-]+@([\\\\w]+\\\\.[\\\\w]+|[\\\\w]+\\\\.[\\\\w]{2,}\\\\.[\\\\w]{2,})$";
        Pattern pattern_Email = Pattern.compile(regex_Email);
        Matcher matcher_Email = pattern_Email.matcher(Email);

        String SDT = txtSDT.getText();
        String regex_SDT = "^0[3785]{1}\\d{8}$";
        Pattern pattern_SDT = Pattern.compile(regex_SDT);
        Matcher matcher_SDT = pattern_SDT.matcher(SDT);

        String CCCD = txtCCCD.getText();
        String regex_CCCD = "^[0-9]{12}$";
        Pattern pattern_CCCD = Pattern.compile(regex_SDT);
        Matcher matcher_CCCD = pattern_CCCD.matcher(CCCD);

        ButtonGroup bg = new ButtonGroup();
        bg.add(RadioNam);
        bg.add(RadioNu);

        String tenTaiKhoan = txtTenTaiKhoan.getText();
        String matKhau = txtMatKhau.getText();
        String xacNhanMatKhau = txtXacNhanMatKhau.getText();
        String vaiTro = "Khách hàng";

        int maKH = 0;
        KhachHang kh1 = new KhachHang();
        List<Integer> listKhachHang;
        try {
            listKhachHang = kh1.listMaKhachHang(vaiTro);

            maKH = listKhachHang.get(listKhachHang.size() - 1) + 1;
            ShareData.maKH = maKH;
            txtMaTaiKhoan.setText(String.valueOf(maKH));
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(DangKyNVienFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        String maKhachHang = "C00" + String.valueOf(maKH);
        int indexKH = 0;
        KhachHang kh = new KhachHang();
        if(RadioNam.isSelected())
            gioiTinh = 0;
        else
            gioiTinh = 1; 

        try {

            if (hoTen.equals("") || diaChi.equals("") || Email.equals("")
                    || SDT.equals("") || CCCD.equals("")
                    || (RadioNam.isSelected() == false && RadioNu.isSelected() == false)) {
                JOptionPane.showMessageDialog(this, "Thông tin chưa đầy đủ",
                        "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            } else if (maKH == kh.getMaKHHienTai(maKH)) {
                JOptionPane.showMessageDialog(this, "Mã khách hàng đã tồn tại",
                        "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            } else if (matcher_SDT.find() == false) {
                JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ",
                        "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            } else if (matcher_Email.find() == false) {
                JOptionPane.showMessageDialog(this, "Email không hợp lệ",
                        "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            } else if (matcher_CCCD.find() == false) {
                JOptionPane.showMessageDialog(this, "CCCD không hợp lệ",
                        "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);            
            } 
            //else
                //indexKH = kh.ThemKhachHang(maKhachHang, hoTen, gioiTinh, diaChi, SDT, Email, CCCD);
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập đã tồn tại");
        }

        // Xử lý thông tin tài khoản 
        int maTK = 0;
        TaiKhoan tk1 = new TaiKhoan();
        List<Integer> listTaiKhoan;
        try {
            listTaiKhoan = tk1.listTK(vaiTro);

            maTK = listTaiKhoan.get(listTaiKhoan.size() - 1) + 1;
            ShareData.maTk = maTK;

            txtMaTaiKhoan.setText(String.valueOf(maTK));
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(DangKyNVienFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        int index = 0;
        TaiKhoan tk = new TaiKhoan();

        try {

            if (tenTaiKhoan.equals("") || matKhau.equals("")
                    || xacNhanMatKhau.equals("") || txtMaTaiKhoan.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Thông tin chưa đầy đủ",
                        "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            } else if (maTK == tk.getMaTKHienTai(maTK)) {
                JOptionPane.showMessageDialog(this, "Mã tài khoản đã tồn tại",
                        "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            } else if (xacNhanMatKhau.equals(matKhau)) {
                index = tk.ThemTaiKhoan(maTK, tenTaiKhoan, matKhau, vaiTro);
            } else {
                JOptionPane.showMessageDialog(this, "Mật khẩu xác nhận không đúng",
                        "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            }
            if (index > 0 && indexKH > 0) {
                JOptionPane.showMessageDialog(this, "Đăng ký thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Tạo tài khoản thất bại");
            }
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }

    }//GEN-LAST:event_btnDangKyActionPerformed

    private void btnTrangDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangDangNhapActionPerformed
        // TODO add your handling code here:
        login = new DangNhapFrame();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnTrangDangNhapActionPerformed

    private void RadioNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioNuActionPerformed

    private void RadioNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioNamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKyKHFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKyKHFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKyKHFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKyKHFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKyKHFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioNam;
    private javax.swing.JRadioButton RadioNu;
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnTaoMoi;
    private javax.swing.JButton btnTrangDangNhap;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbCCCD;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbMaKhachHang;
    private javax.swing.JLabel lbMaTaiKhoan;
    private javax.swing.JLabel lbMatKhau;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbTenKhachHang;
    private javax.swing.JLabel lbTenTaiKhoan;
    private javax.swing.JLabel lbXacNhanMatKhau;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtMaTaiKhoan;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenTaiKhoan;
    private javax.swing.JPasswordField txtXacNhanMatKhau;
    // End of variables declaration//GEN-END:variables
}
