/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import ConnectDB.ConnectionUtils;
import DatabaseProcess.*;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thanh Phat
 */
public class ThongTinNhanVien extends javax.swing.JPanel {
    private DangKyFrame dangKyTaiKhoan;
    private ThongTinNVPanel thongTinPanel;
    /**
     * Creates new form ThongTin
     */
    public ThongTinNhanVien() throws SQLException {
        initComponents();
        loadData();
        this.txtMaTaiKhoan.setEnabled(false);
    }

    
    /**
     * Hàm lấy data nhân viên lên table
     * @throws SQLException 
     */
    private void loadData() throws SQLException{
        try {
            NhanVien nvData = new NhanVien();
            String arr[] = {"Mã nhân viên", "Họ tên", "SĐT","Mã chức vụ",
                    "Ngày sinh" , "Giới tính", "Ngày vào làm", "Email", "Mã tài khoản"};
            List <NhanVien> listNhanVien = nvData.getFullData();
            DefaultTableModel dtm = new DefaultTableModel(arr,0);
            tbThongTinNhanVien.removeAll();
            tbThongTinNhanVien.setModel(dtm);
            
            for (NhanVien nv : listNhanVien) {
                dtm.addRow(new Object[]{
                   nv.getMaNhanVien(), nv.getTenNhanVien()
                  ,nv.getSĐT(),nv.getMaChucVu()
                  ,nv.getNgaySinh(), nv.getGioiTinh()
                  ,nv.getNgayVaoLam(), nv.getEmail()
                  ,nv.getMaTaiKhoan()
                });
            }
            
            dtm.fireTableDataChanged();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ThongTinCacPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbThongTinNhanVien = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnThemNhanVien = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        txtTenNhanVien = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        txtMaViTri = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtMaTaiKhoan = new javax.swing.JTextField();
        txtNgayVaoLam = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        cbbGioiTinh = new javax.swing.JComboBox<>();
        btnLoadLaiDuLieu = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTaoTaiKhoanNhanVien = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtTenTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbThongTinNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Họ tên", "SĐT", "Mã chức vụ", "Ngày sinh", "Giới tính", "Ngày vào làm", "Email", "Mã tài khoản"
            }
        ));
        tbThongTinNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbThongTinNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbThongTinNhanVien);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 111, 1303, 220));

        jPanel1.setToolTipText("Thêm thông tin nhân viên");

        jLabel2.setText("Mã nhân viên: ");

        jLabel3.setText("Tên nhân viên: ");

        jLabel4.setText("Số điện thoại: ");

        jLabel5.setText("Mã chức vụ:");

        jLabel6.setText("Ngày sinh");

        jLabel7.setText("Giới tính");

        jLabel8.setText("Ngày vào làm:");

        btnThemNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_add_database_16px.png"))); // NOI18N
        btnThemNhanVien.setText("Thêm nhân viên");
        btnThemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhanVienActionPerformed(evt);
            }
        });

        jLabel9.setText("Email:");

        jLabel10.setText("Mã tài khoản: ");

        cbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        btnLoadLaiDuLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_restart_16px.png"))); // NOI18N
        btnLoadLaiDuLieu.setText("Làm mới");
        btnLoadLaiDuLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadLaiDuLieuActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_renew_16px.png"))); // NOI18N
        btnUpdate.setText("Sửa thông tin nhân viên");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_delete_database_16px.png"))); // NOI18N
        btnXoa.setText("Xóa nhân viên");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTaoTaiKhoanNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_more_info_16px_1.png"))); // NOI18N
        btnTaoTaiKhoanNhanVien.setText("Tạo tài khoản");
        btnTaoTaiKhoanNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoTaiKhoanNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtMaViTri, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(txtEmail)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtNgayVaoLam)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(50, 50, 50)
                                .addComponent(cbbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnThemNhanVien)
                .addGap(66, 66, 66)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnTaoTaiKhoanNhanVien)
                .addGap(62, 62, 62)
                .addComponent(btnLoadLaiDuLieu)
                .addGap(61, 61, 61)
                .addComponent(btnXoa)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cbbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMaViTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemNhanVien)
                    .addComponent(btnUpdate)
                    .addComponent(btnXoa)
                    .addComponent(btnLoadLaiDuLieu)
                    .addComponent(btnTaoTaiKhoanNhanVien))
                .addGap(43, 43, 43))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 349, -1, -1));

        jLabel11.setText("Tra cứu:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 72, -1, -1));
        add(txtTenTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 69, 179, -1));

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_find_and_replace_16px.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 68, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("THÔNG TIN NHÂN VIÊN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 13, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1320, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoTaiKhoanNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoTaiKhoanNhanVienActionPerformed
        // TODO add your handling code here:
        dangKyTaiKhoan = new DangKyFrame();
        
        dangKyTaiKhoan.setVisible(true);
    }//GEN-LAST:event_btnTaoTaiKhoanNhanVienActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int ret = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa","Xóa nhân viên",JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION){
            String maNhanVienText = txtMaNhanVien.getText();
            if(maNhanVienText.equals(""))
                JOptionPane.showMessageDialog(this, "Không thể để trống mã nhân viên"
                    , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE); 

            int index = 0;

            NhanVien nv = new NhanVien();

            try {
                index = nv.XoaNhanVien(maNhanVienText);

                if(index > 0){
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    loadData();
                }
                else
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
            } catch (SQLException | ClassNotFoundException e) {
                Logger.getLogger(ThongTinNhanVien.class.getName()).log(Level.SEVERE, null, e);
            }

        }  
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLoadLaiDuLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadLaiDuLieuActionPerformed
        try {
            // TODO add your handling code here:
            txtTenTimKiem.setText("");
            loadData();
        } catch (SQLException ex) {
            Logger.getLogger(ThongTinNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.txtMaNhanVien.setEnabled(true);
        txtMaNhanVien.setText("");
        txtTenNhanVien.setText("");
        txtMaTaiKhoan.setText("");
        txtEmail.setText("");
        txtMaViTri.setText("");
        this.txtNgaySinh.setEnabled(true);
        txtNgaySinh.setText("");
        txtSoDienThoai.setText("");
        txtNgayVaoLam.setText("");
        this.cbbGioiTinh.setEnabled(true);
    }//GEN-LAST:event_btnLoadLaiDuLieuActionPerformed

    
    /**
     * Hàm tìm kiếm nhân viên
     * @throws java.sql.SQLException
     */
    public void TimKiemNhanVien() throws SQLException{
        String EmpName_In = txtTenTimKiem.getText();
        try {
            NhanVien nvData = new NhanVien();
            String arr[] = {"Mã nhân viên", "Họ tên", "SĐT","Mã chức vụ",
                    "Ngày sinh" , "Giới tính", "Ngày vào làm", "Email", "Mã tài khoản"};
            List <NhanVien> listNhanVien = nvData.timKiemNhanVien(EmpName_In);
            DefaultTableModel dtm = new DefaultTableModel(arr,0);
            tbThongTinNhanVien.removeAll();
            tbThongTinNhanVien.setModel(dtm);
            for (NhanVien nv : listNhanVien) {
                dtm.addRow(new Object[]{
                   nv.getMaNhanVien(), nv.getTenNhanVien()
                  ,nv.getSĐT(),nv.getMaChucVu()
                  ,nv.getNgaySinh(), nv.getGioiTinh()
                  ,nv.getNgayVaoLam(), nv.getEmail()
                  ,nv.getMaTaiKhoan()
                });
            }
            
            dtm.fireTableDataChanged();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ThongTinCacPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        try {
            // TODO add your handling code here:

            TimKiemNhanVien();
            
        } catch (SQLException ex) {
            Logger.getLogger(ThongTinNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        String maNhanVien = txtMaNhanVien.getText();
        String tenNhanVien = txtTenNhanVien.getText();
        
        String SĐT = txtSoDienThoai.getText();
        String tempSĐT = "^0\\d{9}$";
        Pattern patternSĐT = Pattern.compile(tempSĐT);
        Matcher matcherSĐT = patternSĐT.matcher(SĐT);   
        
        
        String maViTri = txtMaViTri.getText();
        String ngayVaoLam = txtNgayVaoLam.getText();
        
        String email = txtEmail.getText();
        String tempEmail = "^\\w+[a-z0-9]*@{1}\\w+mail.com";
        Pattern pattern = Pattern.compile(tempEmail);
        Matcher matcher = pattern.matcher(email);
        
        int index = 0;
        
        NhanVien nv = new NhanVien();
        
        try {
            
            if(SĐT.length() > 10 || matcherSĐT.find() == false)
                JOptionPane.showMessageDialog(this, "SĐT chỉ có số và có 10 số"
                        , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);  
            else if(matcher.find() == false)
                JOptionPane.showMessageDialog(this, "Email phải có dạng @gmail.com"
                    , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE); 
            else if(maViTri.length() > 5)
                JOptionPane.showMessageDialog(this, "Mã chức vụ có độ dài là 5 bao gồm số và chữ"
                    , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE); 
            else
                index = nv.suaNhanVienDoQL(maNhanVien, tenNhanVien, SĐT, maViTri, ngayVaoLam, email);
            
            if(index > 0){
                JOptionPane.showMessageDialog(this, "Sửa thông tin thành công");
                loadData();
            }
            else
                JOptionPane.showMessageDialog(this, "Sửa thông tin thất bại");
                
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    
    /**
     * Hàm in thông tin lên các TextField
     * @param row 
     */
    private void displayToTextField(int row){
        txtMaNhanVien.setEnabled(false);
        txtMaNhanVien.setText((String) tbThongTinNhanVien.getModel().getValueAt(row, 0));
        
        
        txtTenNhanVien.setText((String) tbThongTinNhanVien.getModel().getValueAt(row, 1));
        
        txtSoDienThoai.setText((String) tbThongTinNhanVien.getModel().getValueAt(row, 2));
        txtMaViTri.setText((String) tbThongTinNhanVien.getModel().getValueAt(row, 3));
        
        txtNgaySinh.setEnabled(false);
        txtNgaySinh.setText((String) tbThongTinNhanVien.getModel().getValueAt(row, 4));
        
        cbbGioiTinh.setEnabled(false);
        String GioiTinh = (String) tbThongTinNhanVien.getModel().getValueAt(row, 5);
        if(GioiTinh.equals("Nữ"))
            cbbGioiTinh.setSelectedIndex(1);
        else
            cbbGioiTinh.setSelectedIndex(0);
        txtNgayVaoLam.setText((String) tbThongTinNhanVien.getModel().getValueAt(row, 6));
        txtEmail.setText((String) tbThongTinNhanVien.getModel().getValueAt(row, 7));
        
        txtMaTaiKhoan.setEnabled(false);
        txtMaTaiKhoan.setText((String) tbThongTinNhanVien.getModel().getValueAt(row, 8));
    }
    
    
    private void tbThongTinNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbThongTinNhanVienMouseClicked
        // TODO add your handling code here:
        
        int row = tbThongTinNhanVien.getSelectedRow();
        
        displayToTextField(row);
    }//GEN-LAST:event_tbThongTinNhanVienMouseClicked

    private void btnThemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhanVienActionPerformed
        // TODO add your handling code here:
        String maNhanVien = txtMaNhanVien.getText();
        String tenNhanVien = txtTenNhanVien.getText();
        
        String SĐT = txtSoDienThoai.getText();
        String tempSĐT = "^[0-9]{10}$";
        Pattern patternSĐT = Pattern.compile(tempSĐT);
        Matcher matcherSĐT = patternSĐT.matcher(SĐT);        
        
        
        String maViTri = txtMaViTri.getText();
        String dob = txtNgaySinh.getText();
        
        String gioiTinh = (String) cbbGioiTinh.getSelectedItem();
        if(gioiTinh.equals("Nam"))
            gioiTinh = "0";
        else
            gioiTinh = "1";
        String ngayVaoLam = txtNgayVaoLam.getText();
        
        String email = txtEmail.getText();
        String tempEmail = "^\\w+[a-z0-9]*@{1}\\w+mail.com";
        Pattern pattern = Pattern.compile(tempEmail);
        Matcher matcher = pattern.matcher(email);
        
        String maTaiKhoan = String.valueOf(ShareData.maTk);
        txtMaTaiKhoan.setText(maTaiKhoan);
        
        int index = 0;
        NhanVien nv = new NhanVien();
        ChucVu cv  = new ChucVu();
        
        try {
            
            if(maNhanVien.equals("") || tenNhanVien.equals("") || SĐT.equals("") 
                    || maViTri.equals("") || dob.equals("") || ngayVaoLam.equals("")
                    || email.equals("") || maTaiKhoan.length() == 0 || gioiTinh.length() == 0)
                    JOptionPane.showMessageDialog(this, "Thông tin chưa đầy đủ"
                        , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE); 
            else if(maNhanVien.equals(nv.getMaNVHienTai(maNhanVien)))
                    JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại"
                        , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE); 
            else if(maNhanVien.length() > 5)
                    JOptionPane.showMessageDialog(this, "Mã nhân viên có độ dài là 5 bao gồm số và chữ"
                        , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE); 
            else if(maViTri.length() > 5)
                    JOptionPane.showMessageDialog(this, "Mã chức vụ có độ dài là 5 bao gồm số và chữ"
                        , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE); 
            else if(maViTri.equals(cv.getMaCVHienTai(maViTri)))
                    JOptionPane.showMessageDialog(this, "Mã chức vụ đã tồn tại"
                        , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE); 
            else if(SĐT.length() > 10 || matcherSĐT.find() == false)
                    JOptionPane.showMessageDialog(this, "SĐT chỉ có số và có 10 số"
                        , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE); 
            else if(email.equals(nv.getEmailHienTai(txtEmail.getText())))
                    JOptionPane.showMessageDialog(this, "Email đã tồn tại"
                        , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE); 
            else if(matcher.find() == false)
                    JOptionPane.showMessageDialog(this, "Email phải dạng ***@gmail.com"
                        , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE); 
            else
                index = nv.ThemNhanVienMoi(maNhanVien, tenNhanVien, SĐT, maViTri, dob
                    , Integer.parseInt(gioiTinh), ngayVaoLam
                    , email, Integer.parseInt(maTaiKhoan));
            
            
            if(index > 0){
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                loadData();
            }
            else
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
                
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Nhân viên chưa đủ 18 tuổi");
        }
    }//GEN-LAST:event_btnThemNhanVienActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadLaiDuLieu;
    private javax.swing.JButton btnTaoTaiKhoanNhanVien;
    private javax.swing.JButton btnThemNhanVien;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbGioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbThongTinNhanVien;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtMaTaiKhoan;
    private javax.swing.JTextField txtMaViTri;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtNgayVaoLam;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JTextField txtTenTimKiem;
    // End of variables declaration//GEN-END:variables
}
