/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import ConnectDB.ConnectionUtils;
import DatabaseProcess.*;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thanh Phat
 */
public class ThongTinChucVuPanel extends javax.swing.JPanel {
    /**
     * Creates new form ThongTinChucVuPanel
     * @throws java.sql.SQLException
     */
    public ThongTinChucVuPanel() throws SQLException {
        initComponents();
        loadData();
        this.txtMaChucVu.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTraCuuMa = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbThongTinChucVu = new javax.swing.JTable();
        btnLamMoi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaChucVu = new javax.swing.JTextField();
        txtTenChucVu = new javax.swing.JTextField();
        txtMaNhanVien = new javax.swing.JTextField();
        btnSuaChucVu = new javax.swing.JButton();
        btnXoaChucVu = new javax.swing.JButton();

        jLabel1.setText("Tra cứu:");

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_find_and_replace_16px.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tbThongTinChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã chức vụ", "Tên chức vụ", "Mã nhân viên"
            }
        ));
        tbThongTinChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbThongTinChucVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbThongTinChucVu);

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_restart_16px.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã chức vụ:");

        jLabel3.setText("Tên chức vụ:");

        jLabel4.setText("Mã nhân viên:");

        txtMaChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaChucVuActionPerformed(evt);
            }
        });

        txtTenChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenChucVuActionPerformed(evt);
            }
        });

        txtMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNhanVienActionPerformed(evt);
            }
        });

        btnSuaChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_renew_16px.png"))); // NOI18N
        btnSuaChucVu.setText("Sửa chức vụ");
        btnSuaChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaChucVuActionPerformed(evt);
            }
        });

        btnXoaChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_delete_database_16px.png"))); // NOI18N
        btnXoaChucVu.setText("Xóa chức vụ");
        btnXoaChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaChucVuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(33, 33, 33))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(31, 31, 31)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaChucVu)
                            .addComponent(txtTenChucVu)
                            .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTraCuuMa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnTimKiem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(btnSuaChucVu)
                        .addGap(70, 70, 70)
                        .addComponent(btnLamMoi)
                        .addGap(47, 47, 47)
                        .addComponent(btnXoaChucVu)))
                .addContainerGap(394, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTraCuuMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaChucVu)
                    .addComponent(btnSuaChucVu)
                    .addComponent(btnLamMoi))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaChucVuActionPerformed

    private void txtMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNhanVienActionPerformed

    private void txtTenChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenChucVuActionPerformed

    
    /**
     * Tìm thông tin chức vụ
     * @throws SQLException 
    */
    private void TimChucVu() throws SQLException{
        String PosNo_In = txtTraCuuMa.getText();
        try {
            ChucVu cvData = new ChucVu();
            String arr[] = {"Mã chức vụ", "Tên chức vụ", "Mã nhân viên"};
            List <ChucVu> listChucVu = cvData.TimChucVu(PosNo_In);
            DefaultTableModel dtm = new DefaultTableModel(arr,0);
            tbThongTinChucVu.removeAll();
            tbThongTinChucVu.setModel(dtm);
            
            for (ChucVu cv : listChucVu) {
                dtm.addRow(new Object[]{
                   cv.getMaChucVu(), cv.getTenChucVu()
                  ,cv.getMaNhanVien()
                });
            }
            
            dtm.fireTableDataChanged();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ThongTinCacPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        try {
            // TODO add your handling code here:
            TimChucVu();
        } catch (SQLException ex) {
            Logger.getLogger(ThongTinChucVuPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        try {
            // TODO add your handling code here:

            loadData();
        } catch (SQLException ex) {
            Logger.getLogger(ThongTinChucVuPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtMaChucVu.setEnabled(true);
        txtMaChucVu.setText("");
        txtMaNhanVien.setText("");
        txtTenChucVu.setText("");
        txtTraCuuMa.setText("");
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnSuaChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaChucVuActionPerformed
        // TODO add your handling code here:
        
        String maChucVu = txtMaChucVu.getText();
        
        String tenChucVu = txtTenChucVu.getText();
        
        String maNhanVien = txtMaNhanVien.getText();
        
        int index = 0;
        ChucVu cv = new ChucVu();
        
        try {
            index = cv.SuaChucVu(maChucVu, tenChucVu, maNhanVien);
            
            if(index > 0){
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                loadData();
            }
            else
                JOptionPane.showMessageDialog(this, "Sửa thất bại");
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
        }
        
    }//GEN-LAST:event_btnSuaChucVuActionPerformed

    private void btnXoaChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaChucVuActionPerformed
        // TODO add your handling code here:
        int ret = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa","Xóa chức vụ",JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION){
            String maChucVu = txtMaChucVu.getText();

            int index = 0;

            ChucVu cv = new ChucVu();

            try {

                if(maChucVu.equals(""))
                    JOptionPane.showMessageDialog(this, "Không thể để trống mã chức vụ"
                        , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE); 
                else
                    index = cv.XoaChucVu(maChucVu);

                if(index > 0){
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    loadData();
                }
                else
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");

            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(this, "Mã chức vụ không tồn tại");
            }
        }          
    }//GEN-LAST:event_btnXoaChucVuActionPerformed

    
    /**
     * Hàm biểu diễn thông tin lên TextField
     * @param row 
     */
    private void displayToTextField(int row){
        txtMaChucVu.setEnabled(false);
        txtMaChucVu.setText((String) tbThongTinChucVu.getModel().getValueAt(row, 0));
        
        txtTenChucVu.setText((String) tbThongTinChucVu.getModel().getValueAt(row, 1));
        
        txtMaNhanVien.setText((String) tbThongTinChucVu.getModel().getValueAt(row, 2));
    }
    
    
    private void tbThongTinChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbThongTinChucVuMouseClicked
        // TODO add your handling code here:
        
        int row = tbThongTinChucVu.getSelectedRow();
        
        displayToTextField(row);
        
    }//GEN-LAST:event_tbThongTinChucVuMouseClicked

    
    /**
     * Load thông tin chức vụ lên table
     * @throws SQLException 
     */
    private void loadData() throws SQLException{
        try {
            ChucVu cvData = new ChucVu();
            String arr[] = {"Mã chức vụ", "Tên chức vụ", "Mã nhân viên"};
            List <ChucVu> listChucVu = cvData.getFullData();
            DefaultTableModel dtm = new DefaultTableModel(arr,0);
            tbThongTinChucVu.removeAll();
            tbThongTinChucVu.setModel(dtm);
            
            for (ChucVu cv : listChucVu) {
                dtm.addRow(new Object[]{
                   cv.getMaChucVu(), cv.getTenChucVu()
                  ,cv.getMaNhanVien()
                });
            }
            
            dtm.fireTableDataChanged();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ThongTinCacPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSuaChucVu;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoaChucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbThongTinChucVu;
    private javax.swing.JTextField txtMaChucVu;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtTenChucVu;
    private javax.swing.JTextField txtTraCuuMa;
    // End of variables declaration//GEN-END:variables
}
