/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import ConnectDB.ConnectionUtils;
import DatabaseProcess.*;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thanh Phat
 */
public class ThongTinDichVuDaDat extends javax.swing.JPanel {

    /**
     * Creates new form CacDichVuDaDat
     * @throws java.sql.SQLException
     */
    public ThongTinDichVuDaDat() throws SQLException {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbThongTinDichVuDaDat = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnThemDichVu = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnSuaDichVu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        txtMaDichVu = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();

        tbThongTinDichVuDaDat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Mã dịch vụ", "Ghi chú"
            }
        ));
        tbThongTinDichVuDaDat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbThongTinDichVuDaDatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbThongTinDichVuDaDat);

        jLabel1.setText("Tra cứu dịch vụ của mã phòng: ");

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_find_and_replace_16px.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnThemDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_add_database_16px.png"))); // NOI18N
        btnThemDichVu.setText("Thêm dịch vụ cho khách hàng");

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_restart_16px.png"))); // NOI18N
        btnRefresh.setText("Làm mới");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnSuaDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_renew_16px.png"))); // NOI18N
        btnSuaDichVu.setText("Sửa ghi chú dịch vụ gọi");
        btnSuaDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDichVuActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã phòng:");

        jLabel3.setText("Mã dịch vụ:");

        jLabel4.setText("Ghi chú");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_delete_database_16px.png"))); // NOI18N
        jButton2.setText("Xóa dịch vụ");

        jLabel5.setText("Mã hóa đơn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThemDichVu)
                                .addGap(47, 47, 47)
                                .addComponent(btnRefresh)
                                .addGap(52, 52, 52)
                                .addComponent(btnSuaDichVu)
                                .addGap(39, 39, 39)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jLabel5)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimKiem)
                .addGap(333, 333, 333))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThemDichVu)
                        .addComponent(btnRefresh))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSuaDichVu)
                        .addComponent(jButton2)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Hàm tìm dịch vụ đã đặt
     * @throws SQLException 
     */
    private void FindDichVu() throws SQLException, ClassNotFoundException{
        String maPhong = txtTimKiem.getText();
        try {
            DichVu dvData = new DichVu();
            String arr[] = {"Mã hóa đơn", "Mã phòng", "Mã dịch vụ", "Ghi chú"};
            List <DichVu> listDichVu = dvData.TimDichVuDaDat(maPhong);
            DefaultTableModel dtm = new DefaultTableModel(arr,0);
            tbThongTinDichVuDaDat.removeAll();
            tbThongTinDichVuDaDat.setModel(dtm);
            
            for (DichVu dv : listDichVu) {
                dtm.addRow(new Object[]{
                   dv.getMaHoaDon()
                  ,dv.getMaPhong(), dv.getMaDichVuString()
                  ,dv.getGhiChu()
                });
            }
            
            dtm.fireTableDataChanged();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }
    
    
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        try {
            // TODO add your handling code here:

            FindDichVu();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ThongTinDichVuDaDat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        try {
            // TODO add your handling code here:

            loadData();
        } catch (SQLException ex) {
            Logger.getLogger(ThongTinHoaDonPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtTimKiem.setText("");
        txtMaHoaDon.setEnabled(true);
        txtMaHoaDon.setText("");
        txtMaPhong.setEnabled(true);
        txtMaPhong.setText("");
        txtMaDichVu.setEnabled(true);
        txtMaDichVu.setText("");
        txtGhiChu.setText("");
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * Biểu diễn thông tin lên JTextField
     * @param row 
     */
    private void displayToTextField(int row){
        txtMaHoaDon.setEnabled(false);
        txtMaHoaDon.setText((String) tbThongTinDichVuDaDat.getModel().getValueAt(row, 0));
        
        txtMaPhong.setEnabled(false);
        txtMaPhong.setText((String) tbThongTinDichVuDaDat.getModel().getValueAt(row, 1));
        
        txtMaDichVu.setEnabled(false);
        txtMaDichVu.setText((String) tbThongTinDichVuDaDat.getModel().getValueAt(row, 2));
        
        txtGhiChu.setText((String) tbThongTinDichVuDaDat.getModel().getValueAt(row, 3));
    }
    
    private void tbThongTinDichVuDaDatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbThongTinDichVuDaDatMouseClicked
        // TODO add your handling code here:
        int row = tbThongTinDichVuDaDat.getSelectedRow();
        
        
        displayToTextField(row);
    }//GEN-LAST:event_tbThongTinDichVuDaDatMouseClicked

    private void btnSuaDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDichVuActionPerformed
        // TODO add your handling code here:
        String maPhong = txtMaPhong.getText();
        String maHoaDon = txtMaHoaDon.getText();
        String maDichVu = txtMaDichVu.getText();
        String ghiChu  = txtGhiChu.getText();
        
        
        int index = 0;
        DichVu dv = new DichVu();
        
        try {
            
            if(ghiChu.equals(""))
                JOptionPane.showMessageDialog(this, "Không thể để trống ghi chú"
                    , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE); 
            else
                index = dv.suaDichVuDaDat(maPhong, maHoaDon, maDichVu, ghiChu);
            
            if(index > 0){
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                loadData();
            }
            else {
                JOptionPane.showMessageDialog(this, "Sửa thất bại");
            }
            
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.toString()); 
        }
        
    }//GEN-LAST:event_btnSuaDichVuActionPerformed

    
    /**
     * Tìm các dịch vụ đã được đặt
     * @throws SQLException 
     */
    private void loadData() throws SQLException{
        try {
            DichVu dvData = new DichVu();
            String arr[] = {"Mã hóa đơn", "Mã phòng", "Mã dịch vụ", "Ghi chú"};
            List <DichVu> listDichVu = dvData.DichVuDaDat();
            DefaultTableModel dtm = new DefaultTableModel(arr,0);
            tbThongTinDichVuDaDat.removeAll();
            tbThongTinDichVuDaDat.setModel(dtm);
            
            for (DichVu dv : listDichVu) {
                dtm.addRow(new Object[]{
                   dv.getMaHoaDon()
                  ,dv.getMaPhong(), dv.getMaDichVuString()
                  ,dv.getGhiChu()
                });
            }
            
            dtm.fireTableDataChanged();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ThongTinCacPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSuaDichVu;
    private javax.swing.JButton btnThemDichVu;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbThongTinDichVuDaDat;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaDichVu;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
