/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import ConnectDB.ConnectionUtils;
import DatabaseProcess.*;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thanh Phat
 */
public class ThongTinCacTaiKhoan extends javax.swing.JPanel {
    /**
     * Creates new form ThongTinCacTaiKhoanNhanVien
     * @throws java.sql.SQLException
     */
    public ThongTinCacTaiKhoan() throws SQLException {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbThongTinCacTaiKhoan = new javax.swing.JTable();
        txtMaTimKiemTen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnTraCuu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaTaiKhoan = new javax.swing.JTextField();
        txtTenTaiKhoan = new javax.swing.JTextField();
        txtVaiTro = new javax.swing.JTextField();
        btnSuaThongTin = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXoaTaiKhoan = new javax.swing.JButton();

        tbThongTinCacTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tài khoản", "Tên tài khoản", "Vai trò"
            }
        ));
        tbThongTinCacTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbThongTinCacTaiKhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbThongTinCacTaiKhoan);

        jLabel1.setText("Tra cứu:");

        btnTraCuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_find_and_replace_16px.png"))); // NOI18N
        btnTraCuu.setText("Tìm kiếm");
        btnTraCuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraCuuActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã tài khoản:");

        jLabel3.setText("Tên tài khoản:");

        jLabel5.setText("Vai trò:");

        btnSuaThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_renew_16px.png"))); // NOI18N
        btnSuaThongTin.setText("Sửa thông tin");
        btnSuaThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaThongTinActionPerformed(evt);
            }
        });

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_restart_16px.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXoaTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_delete_database_16px.png"))); // NOI18N
        btnXoaTaiKhoan.setText("Xóa tài khoản");
        btnXoaTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTaiKhoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaTimKiemTen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnTraCuu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSuaThongTin)
                                .addGap(101, 101, 101)
                                .addComponent(btnLamMoi)
                                .addGap(96, 96, 96)
                                .addComponent(btnXoaTaiKhoan))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(35, 35, 35)
                                        .addComponent(txtMaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(33, 33, 33)
                                        .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(98, 98, 98)
                                .addComponent(jLabel5)
                                .addGap(29, 29, 29)
                                .addComponent(txtVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaTimKiemTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnTraCuu))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuaThongTin)
                    .addComponent(btnLamMoi)
                    .addComponent(btnXoaTaiKhoan))
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTaiKhoanActionPerformed
        // TODO add your handling code here:
        int ret = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa","Xóa tài khoản",JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION){
            String maTaiKhoan = txtMaTaiKhoan.getText();

            int index = 0;

            TaiKhoan tk = new TaiKhoan();

            try {
                if(maTaiKhoan.equals(""))
                    JOptionPane.showMessageDialog(this, "Không thể để trống mã tài khoản"
                        , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE); 
                else
                    index = tk.XoaTaiKhoan(Integer.parseInt(maTaiKhoan));

                if(index > 0){
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    loadData();
                }
                else
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
            } catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.INFORMATION_MESSAGE);
            }
        }  
    }//GEN-LAST:event_btnXoaTaiKhoanActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        try {
            // TODO add your handling code here:
            txtMaTimKiemTen.setText("");
            loadData();
        } catch (SQLException ex) {
            Logger.getLogger(ThongTinCacTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtMaTaiKhoan.setEnabled(true);
        txtMaTaiKhoan.setText("");
        
        txtTenTaiKhoan.setEnabled(true);
        txtTenTaiKhoan.setText("");
        
        txtVaiTro.setEnabled(true);
        txtVaiTro.setText("");
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnSuaThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaThongTinActionPerformed
        // TODO add your handling code here:
        
        String maTaiKhoan = txtMaTaiKhoan.getText();
        String vaiTro = txtVaiTro.getText();
        
        int index = 0;
        TaiKhoan tk = new TaiKhoan();
        
        try {
            if(vaiTro.equals(""))
                JOptionPane.showMessageDialog(this, "Thông tin chưa đầy đủ"
                    , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE); 
            else
                index = tk.SuaTaiKhoan(Integer.parseInt(maTaiKhoan), vaiTro);
            
            
            if(index > 0){
                JOptionPane.showMessageDialog(this, "Sửa thông tin thành công");
                loadData();
            }
            else
                JOptionPane.showMessageDialog(this, "Sửa thông tin thất bại");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSuaThongTinActionPerformed

    /**
     * Hàm tìm tài khoản
     * @throws SQLException 
     */
    private void TraCuuTaiKhoan() throws SQLException{
        String tenTaiKhoan = txtMaTimKiemTen.getText();
        try {
            TaiKhoan tkData = new TaiKhoan();
            String arr[] = {"Mã tài khoản" , "Tên đăng nhập", "Vai trò"};
            List <User> listTaiKhoan = tkData.TimTaiKhoan(tenTaiKhoan);
            DefaultTableModel dtm = new DefaultTableModel(arr,0);
            tbThongTinCacTaiKhoan.removeAll();
            tbThongTinCacTaiKhoan.setModel(dtm);
            
            for (User us : listTaiKhoan) {
                dtm.addRow(new Object[]{
                    us.getMaTaiKhoan(), us.getTenDangNhapString()
                   ,us.getVaiTro()
                });
            }
            
            dtm.fireTableDataChanged();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ThongTinCacPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btnTraCuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraCuuActionPerformed
        try {
            // TODO add your handling code here:

            TraCuuTaiKhoan();
        } catch (SQLException ex) {
            Logger.getLogger(ThongTinCacTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTraCuuActionPerformed

    /**
     * Hàm biễu diễn dữ liệu lên các textfield
     * @param row 
     */
    private void displayToTextField(int row){
        txtMaTaiKhoan.setEnabled(false);
        txtMaTaiKhoan.setText((String) tbThongTinCacTaiKhoan.getModel().getValueAt(row, 0));
        
        txtTenTaiKhoan.setEnabled(false);
        txtTenTaiKhoan.setText((String) tbThongTinCacTaiKhoan.getModel().getValueAt(row, 1));
        
        
        txtVaiTro.setText((String) tbThongTinCacTaiKhoan.getModel().getValueAt(row, 2)); 
        
    }
    private void tbThongTinCacTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbThongTinCacTaiKhoanMouseClicked
        // TODO add your handling code here:
        
        int row = tbThongTinCacTaiKhoan.getSelectedRow();
        
        displayToTextField(row);
    }//GEN-LAST:event_tbThongTinCacTaiKhoanMouseClicked

    
    /**
     * Hàm load data lên table
     * @throws SQLException 
     */
    private void loadData() throws SQLException{
        try {
            TaiKhoan tkData = new TaiKhoan();
            String arr[] = {"Mã tài khoản" , "Tên đăng nhập", "Vai trò"};
            List <User> listTaiKhoan = tkData.getFullData();
            DefaultTableModel dtm = new DefaultTableModel(arr,0);
            tbThongTinCacTaiKhoan.removeAll();
            tbThongTinCacTaiKhoan.setModel(dtm);
            
            for (User us : listTaiKhoan) {
                dtm.addRow(new Object[]{
                    us.getMaTaiKhoan(), us.getTenDangNhapString()
                   ,us.getVaiTro()
                });
            }
            
            dtm.fireTableDataChanged();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ThongTinCacPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSuaThongTin;
    private javax.swing.JButton btnTraCuu;
    private javax.swing.JButton btnXoaTaiKhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbThongTinCacTaiKhoan;
    private javax.swing.JTextField txtMaTaiKhoan;
    private javax.swing.JTextField txtMaTimKiemTen;
    private javax.swing.JTextField txtTenTaiKhoan;
    private javax.swing.JTextField txtVaiTro;
    // End of variables declaration//GEN-END:variables
}
