/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import ConnectDB.ConnectionUtils;
import DatabaseProcess.*;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thanh Phat
 */
public class ThongTinDichVuPanel extends javax.swing.JPanel {
    /**
     * Creates new form ThongTinDichVuPanel
     * @throws java.sql.SQLException
     */
    public ThongTinDichVuPanel() throws SQLException {
        initComponents();
        loadData();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTraCuu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbThongTinDichVu = new javax.swing.JTable();
        btnLamMoi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaDichVu = new javax.swing.JTextField();
        txtTenDichVu = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        cbbLoaiHinh = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Tra cứu dịch vụ:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 55, -1, -1));
        add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 120, -1));

        btnTraCuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_find_and_replace_16px.png"))); // NOI18N
        btnTraCuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraCuuActionPerformed(evt);
            }
        });
        add(btnTraCuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        tbThongTinDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Loại hình", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbThongTinDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbThongTinDichVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbThongTinDichVu);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 680, 235));

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_restart_16px.png"))); // NOI18N
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Mã dịch vụ:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Tên dịch vụ:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Loại hình:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Giá:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 58, -1));
        add(txtMaDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 110, 30));
        add(txtTenDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 172, 110, 30));
        add(txtGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 113, 30));

        cbbLoaiHinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngoài trời", "Trong nhà" }));
        add(cbbLoaiHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, 90, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/Màn hình đăng nhập.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 1410, 590));
    }// </editor-fold>//GEN-END:initComponents

    
        
    /**
     * Hàm tra cứu dịch vụ
     */
    private void FindDichVu() throws SQLException{
        String SerNo_In = txtTimKiem.getText();
        try {
            DichVu dvData = new DichVu();
            String arr[] = {"Mã dịch vụ", "Tên dịch vụ", "Loại hình", "Giá"};
            List <DichVu> listDichVu = dvData.FinđichVu(SerNo_In);
            DefaultTableModel dtm = new DefaultTableModel(arr,0);
            tbThongTinDichVu.removeAll();
            tbThongTinDichVu.setModel(dtm);
            
            for (DichVu dv : listDichVu) {
                dtm.addRow(new Object[]{
                  dv.getMaDichVuString(), dv.getTenDichVu()
                 ,dv.getLoaiHinh(), dv.getGia()
                });
            }
            
            dtm.fireTableDataChanged();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ThongTinCacPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btnTraCuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraCuuActionPerformed
        try {
            // TODO add your handling code here:

            FindDichVu();
        } catch (SQLException ex) {
            Logger.getLogger(ThongTinDichVuPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnTraCuuActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        if(ShareData.useraccount.getVaiTro().equals("Nhân viên")){
            txtMaDichVu.setEnabled(false);
            txtGia.setEnabled(false);
            txtTenDichVu.setEnabled(false);
            cbbLoaiHinh.setEnabled(false);
        }
        else
           txtMaDichVu.setEnabled(true); 
        try {
            // TODO add your handling code here:
            loadData();
        } catch (SQLException ex) {
            Logger.getLogger(ThongTinDichVuPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtMaDichVu.setText("");
        txtTenDichVu.setText("");
        txtGia.setText("");
        txtTimKiem.setText("");
    }//GEN-LAST:event_btnLamMoiActionPerformed

    
        /**
     * Hàm in thông tin lên các TextField
     * @param row 
     */
    private void displayToTextField(int row){
        txtMaDichVu.setEnabled(false);
        txtMaDichVu.setText((String) tbThongTinDichVu.getModel().getValueAt(row, 0));
        
        txtTenDichVu.setText((String) tbThongTinDichVu.getModel().getValueAt(row, 1));
        
        String loaiHinh = (String) tbThongTinDichVu.getModel().getValueAt(row, 2);
        if(loaiHinh.equals("Ngoài trời"))
            cbbLoaiHinh.setSelectedIndex(0);
        else
            cbbLoaiHinh.setSelectedIndex(1);
        
        txtGia.setText((String) tbThongTinDichVu.getModel().getValueAt(row, 3));
    }
    
    
    private void tbThongTinDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbThongTinDichVuMouseClicked
        // TODO add your handling code here:
        int row = tbThongTinDichVu.getSelectedRow();
        
        displayToTextField(row);
    }//GEN-LAST:event_tbThongTinDichVuMouseClicked


    /**
     * Hàm lấy thông tin các dịch vụ trong khách sạn
     * @throws SQLException 
     */
    private void loadData() throws SQLException{
        try {
            DichVu dvData = new DichVu();
            String arr[] = {"Mã dịch vụ", "Tên dịch vụ", "Loại hình", "Giá"};
            List <DichVu> listDichVu = dvData.getFullData();
            DefaultTableModel dtm = new DefaultTableModel(arr,0);
            tbThongTinDichVu.removeAll();
            tbThongTinDichVu.setModel(dtm);
            
            for (DichVu dv : listDichVu) {
                dtm.addRow(new Object[]{
                  dv.getMaDichVuString(), dv.getTenDichVu()
                 ,dv.getLoaiHinh(), dv.getGia()
                });
            }
            
            dtm.fireTableDataChanged();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ThongTinCacPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnTraCuu;
    private javax.swing.JComboBox<String> cbbLoaiHinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbThongTinDichVu;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaDichVu;
    private javax.swing.JTextField txtTenDichVu;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
