/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import ConnectDB.ConnectionUtils;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import DatabaseProcess.Room;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Thanh Phat
 */
public class ThongTinCacPhong extends javax.swing.JPanel {

    public ThongTinCacPhong(  JButton btnSuaPhong, JButton btnThemPhong, JButton btnThoat, JButton btnXoaPhong, JLabel jLabel1, JScrollPane jScrollPane1, JTabbedPane jTabbedPane1, JTable tbThongTinPhong, JTabbedPane tplThemPhong, JTabbedPane tplXoaPhong) {

        this.btnSuaPhong = btnSuaPhong;
        this.btnXoaPhong = btnXoaPhong;
        this.jScrollPane1 = jScrollPane1;
        this.jTabbedPane1 = jTabbedPane1;
        this.tbThongTinPhong = tbThongTinPhong;
    }
    /**
     * Creates new form RoomManagement
     * @throws java.sql.SQLException
     */
    public ThongTinCacPhong() throws SQLException {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        btnXoaPhong = new javax.swing.JButton();
        btnSuaPhong = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbThongTinPhong = new javax.swing.JTable();
        btnThemPhong1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtMaPhongTimKiem = new javax.swing.JTextField();
        btnTraCuu = new javax.swing.JButton();
        btnLoadLoaiDuLieu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        cbbLoaiPhong = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbbChatLuong = new javax.swing.JComboBox<>();
        txtGiaPhong = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnXoaPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_delete_database_16px.png"))); // NOI18N
        btnXoaPhong.setText("Xóa phòng");
        btnXoaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPhongActionPerformed(evt);
            }
        });
        add(btnXoaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 563, -1, -1));

        btnSuaPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_renew_16px.png"))); // NOI18N
        btnSuaPhong.setText("Sửa thông tin phòng");
        btnSuaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaPhongActionPerformed(evt);
            }
        });
        add(btnSuaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 563, -1, -1));

        tbThongTinPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Loại phòng", "Chất lượng", "Giá"
            }
        ));
        tbThongTinPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbThongTinPhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbThongTinPhong);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 107, 1380, 250));

        btnThemPhong1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_add_database_16px.png"))); // NOI18N
        btnThemPhong1.setText("Thêm phòng");
        btnThemPhong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPhong1ActionPerformed(evt);
            }
        });
        add(btnThemPhong1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 563, -1, -1));

        jLabel7.setText("Tra cứu:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 75, -1, -1));
        add(txtMaPhongTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 72, 148, -1));

        btnTraCuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_find_and_replace_16px.png"))); // NOI18N
        btnTraCuu.setText("Tìm kiếm");
        btnTraCuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraCuuActionPerformed(evt);
            }
        });
        add(btnTraCuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 71, -1, -1));

        btnLoadLoaiDuLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_restart_16px.png"))); // NOI18N
        btnLoadLoaiDuLieu.setText("Làm mới");
        btnLoadLoaiDuLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadLoaiDuLieuActionPerformed(evt);
            }
        });
        add(btnLoadLoaiDuLieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 563, -1, -1));

        jLabel2.setText("Mã phòng: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 378, -1, -1));

        jLabel4.setText("Loại phòng; ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 413, -1, -1));

        jLabel5.setText("Chất lượng phòng:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 456, -1, -1));

        jLabel6.setText("Giá phòng:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 496, -1, -1));
        add(txtMaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 375, 63, -1));

        cbbLoaiPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        cbbLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLoaiPhongActionPerformed(evt);
            }
        });
        add(cbbLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 413, -1, -1));

        jLabel3.setText("giường");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 416, 62, -1));

        cbbChatLuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Superior", "Deluxe" }));
        cbbChatLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChatLuongActionPerformed(evt);
            }
        });
        add(cbbChatLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 453, 115, -1));
        add(txtGiaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 493, 115, -1));

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("THÔNG TIN CÁC PHÒNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(544, 544, 544)
                .addComponent(jLabel1)
                .addContainerGap(568, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 60));
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Hàm tìm tất cả phòng
     * @throws SQLException 
     */
    public void loadData() throws SQLException{
        try {
            Room roomData = new Room();
            String arr[] = {"Mã phòng", "Loại phòng", "Chất lượng","Giá"};
            List <Room> listRoom = roomData.getFullData();
            DefaultTableModel dtm = new DefaultTableModel(arr,0);
            tbThongTinPhong.removeAll();
            tbThongTinPhong.setModel(dtm);
            
            for (Room room : listRoom) {
                dtm.addRow(new Object[]{
                    room.getMaPhong(), room.getLoaiPhong()
                        , room.getChatLuongPhong(),room.getGia()
                });
            }
            
            dtm.fireTableDataChanged();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ThongTinCacPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnXoaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPhongActionPerformed
        // TODO add your handling code here:
        
        int ret = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa","Xóa phòng",JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION){
            String MaPhongtext = txtMaPhong.getText();
            Room r = new Room();

            int index = 0;

            try {
                if(MaPhongtext.equals(""))
                    JOptionPane.showMessageDialog(this, "Không thể để trống mã phòng"
                        , "Lỗi xóa thông tin", JOptionPane.ERROR_MESSAGE);  
                else
                    index = r.XoaPhong(MaPhongtext);    
                if (index > 0) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    loadData();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                }
            }catch (SQLException | ClassNotFoundException  ex) {
                Logger.getLogger(ThongTinCacPhong.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
        
    }//GEN-LAST:event_btnXoaPhongActionPerformed

    private void btnSuaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaPhongActionPerformed
        // TODO add your handling code here:
       
        String maPhongText = txtMaPhong.getText();

        String giaPhongText = txtGiaPhong.getText();
        
        String LoaiPhongtext = (String) cbbLoaiPhong.getSelectedItem();
        
        Room r = new Room();
        
        int index = 0;
        
        try {
            if(maPhongText.equals("") || giaPhongText.equals(""))
                JOptionPane.showMessageDialog(this, "Thông tin chưa đầy đủ"
                        , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);  
            else
                index = r.SuaPhong(maPhongText, LoaiPhongtext, giaPhongText);
            
            if(index > 0){
                JOptionPane.showMessageDialog(this, "Sửa thông tin thành công");
                loadData();
            }
            else
                JOptionPane.showMessageDialog(this, "Sửa thông tin thất bại");
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
        }
    }//GEN-LAST:event_btnSuaPhongActionPerformed

    private void btnThemPhong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPhong1ActionPerformed
        // TODO add your handling code here:

        String MaPhongtext = txtMaPhong.getText();
        String LoaiPhongtext = (String) cbbLoaiPhong.getSelectedItem();
        String chatLuongtext = (String) cbbChatLuong.getSelectedItem();
        String giaPhongtext = "";
        
        if(LoaiPhongtext.equals("1") && chatLuongtext.equals("Standard"))
        {
            txtGiaPhong.setText("200000");
            giaPhongtext = txtGiaPhong.getText();
        }
        else if(LoaiPhongtext.equals("1") && chatLuongtext.equals("Superior"))
        {
            txtGiaPhong.setText("250000");
            giaPhongtext = txtGiaPhong.getText();            
        }
        else if(LoaiPhongtext.equals("1") && chatLuongtext.equals("Deluxe"))
        {
            txtGiaPhong.setText("300000");
            giaPhongtext = txtGiaPhong.getText();            
        }
        else if(LoaiPhongtext.equals("2") && chatLuongtext.equals("Standard"))
        {
            txtGiaPhong.setText("450000");
            giaPhongtext = txtGiaPhong.getText();            
        } 
        else if(LoaiPhongtext.equals("2") && chatLuongtext.equals("Superior"))
        {
            txtGiaPhong.setText("500000");
            giaPhongtext = txtGiaPhong.getText();            
        }   
        else if(LoaiPhongtext.equals("2") && chatLuongtext.equals("Deluxe "))
        {
            txtGiaPhong.setText("550000");
            giaPhongtext = txtGiaPhong.getText();            
        }   
        
        
        Room r = new Room();
        int index = 0;
        try {
            try {
            if(MaPhongtext.equals("")|| giaPhongtext.equals(""))
                JOptionPane.showMessageDialog(this, "Thông tin chưa đầy đủ"
                        , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE); 
            else if(MaPhongtext.length() > 5)
                JOptionPane.showMessageDialog(this, "Mã phòng có độ dài là 5 bao gồm cả số và chữ"
                        , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE); 
            else if(MaPhongtext.equals(r.getMaPhongHienTai(MaPhongtext)))
                JOptionPane.showMessageDialog(this, "Mã phòng đã tồn tại"
                        , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE); 
            else
                index = r.ThemPhongMoi(MaPhongtext, LoaiPhongtext, chatLuongtext, giaPhongtext);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ThongTinCacPhong.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if (index > 0) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        }catch (SQLException  ex) {
            //JOptionPane.showMessageDialog(this, "Một lỗi gì đó");
        }
    }//GEN-LAST:event_btnThemPhong1ActionPerformed

    private void cbbLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoaiPhongActionPerformed
        // TODO add your handling code here:
        String selectItem = (String) cbbLoaiPhong.getSelectedItem();
    }//GEN-LAST:event_cbbLoaiPhongActionPerformed

    private void cbbChatLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChatLuongActionPerformed
        // TODO add your handling code here:
        String selectItem = (String) cbbChatLuong.getSelectedItem();
    }//GEN-LAST:event_cbbChatLuongActionPerformed

    
    /**
     * Hàm tìm phòng
     * @throws SQLException 
     */
    public void findRoom() throws SQLException{
        PreparedStatement pstm = null;
        ResultSet rs = null;
        String RoomNo_In = txtMaPhongTimKiem.getText();
        try {
            Connection conn = ConnectionUtils.getMyConnection();
            Room roomData = new Room();
            String arr[] = {"Mã phòng", "Loại phòng", "Chất lượng","Giá"};
            List <Room> listRoom = roomData.traCuuPhong(RoomNo_In);
            DefaultTableModel dtm = new DefaultTableModel(arr,0);
            tbThongTinPhong.removeAll();
            tbThongTinPhong.setModel(dtm);
            
            for (Room room : listRoom) {
                dtm.addRow(new Object[]{
                    room.getMaPhong(), room.getLoaiPhong()
                        , room.getChatLuongPhong(),room.getGia()
                });
            }
            
            dtm.fireTableDataChanged();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ThongTinCacPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btnTraCuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraCuuActionPerformed
        try {
            // TODO add your handling code here:

            findRoom();
        } catch (SQLException ex) {
            Logger.getLogger(ThongTinCacPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTraCuuActionPerformed

    private void btnLoadLoaiDuLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadLoaiDuLieuActionPerformed
        try {
            // TODO add your handling code here:
            txtMaPhongTimKiem.setText("");
            loadData();
        } catch (SQLException ex) {
            Logger.getLogger(ThongTinCacPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtMaPhong.setEnabled(true);
        txtMaPhong.setText("");
        txtGiaPhong.setText("");
        cbbChatLuong.setEnabled(true);
    }//GEN-LAST:event_btnLoadLoaiDuLieuActionPerformed

    /**
     * Hàm load dữ liệu lên text field
     * @param row 
     */
    private void displayToTextField(int row){
        txtMaPhong.setEnabled(false);
        txtMaPhong.setText((String)tbThongTinPhong.getModel().getValueAt(row, 0));
        
        String loaiHinh = (String) tbThongTinPhong.getModel().getValueAt(row, 1);
        if(loaiHinh.equals("1"))
            cbbLoaiPhong.setSelectedIndex(0);
        else
            cbbLoaiPhong.setSelectedIndex(1);
        
        cbbChatLuong.setEnabled(false);
        String chatLuong = (String) tbThongTinPhong.getModel().getValueAt(row, 2);
        switch (chatLuong) {
            case "Standard" -> cbbChatLuong.setSelectedIndex(0);
            case "Superior" -> cbbChatLuong.setSelectedIndex(1);
            default -> cbbChatLuong.setSelectedIndex(2);
        }
        
        txtGiaPhong.setText((String)tbThongTinPhong.getModel().getValueAt(row, 3));
    }
    
    
    private void tbThongTinPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbThongTinPhongMouseClicked
        // TODO add your handling code here:
        
        int row = tbThongTinPhong.getSelectedRow();
        
        displayToTextField(row);
    }//GEN-LAST:event_tbThongTinPhongMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadLoaiDuLieu;
    private javax.swing.JButton btnSuaPhong;
    private javax.swing.JButton btnThemPhong1;
    private javax.swing.JButton btnTraCuu;
    private javax.swing.JButton btnXoaPhong;
    private javax.swing.JComboBox<String> cbbChatLuong;
    private javax.swing.JComboBox<String> cbbLoaiPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbThongTinPhong;
    private javax.swing.JTextField txtGiaPhong;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtMaPhongTimKiem;
    // End of variables declaration//GEN-END:variables
}
