/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import ConnectDB.ConnectionUtils;
import DatabaseProcess.*;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thanh Phat
 */
public class ThongTinVatDungPhongPanel extends javax.swing.JPanel {
    /**
     * Creates new form ThongTinVatDungPhongPanel
     * @throws java.sql.SQLException
     */
    public ThongTinVatDungPhongPanel() throws SQLException {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbThongTinVatDung = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        txtMaVatDung = new javax.swing.JTextField();
        txtTenVatDung = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        cbbTinhTrang = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnSuaThongTin = new javax.swing.JButton();
        btnXoaVatDung = new javax.swing.JButton();

        jLabel1.setText("Tra cứu:");

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_find_and_replace_16px.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tbThongTinVatDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Mã vật dụng", "Tên vật dụng", "Số lượng", "Tình trạng"
            }
        ));
        tbThongTinVatDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbThongTinVatDungMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbThongTinVatDung);

        jLabel2.setText("Mã phòng:");

        jLabel3.setText("Mã vật dụng:");

        jLabel4.setText("Tên vật dụng:");

        jLabel5.setText("Số lượng:");

        jLabel6.setText("Tình trạng:");

        cbbTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tốt", "Hư hỏng", "Chưa trang bị" }));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_add_database_16px.png"))); // NOI18N
        btnThem.setText("Thêm vật dụng");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_restart_16px.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnSuaThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_renew_16px.png"))); // NOI18N
        btnSuaThongTin.setText("Sửa thông tin");
        btnSuaThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaThongTinActionPerformed(evt);
            }
        });

        btnXoaVatDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Source/icons8_delete_database_16px.png"))); // NOI18N
        btnXoaVatDung.setText("Xóa vật dụng");
        btnXoaVatDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaVatDungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimKiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(btnThem)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLamMoi)
                        .addGap(100, 100, 100)
                        .addComponent(btnSuaThongTin)
                        .addGap(100, 100, 100)
                        .addComponent(btnXoaVatDung))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42)
                        .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenVatDung, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(txtSoLuong)
                            .addComponent(cbbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaVatDung))))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaVatDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTenVatDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSuaThongTin)
                        .addComponent(btnXoaVatDung)
                        .addComponent(btnLamMoi)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Hàm tìm vật dụng
     * @throws SQLException 
     */
    public void timVatDung() throws SQLException{
        String tenVatDung = txtTimKiem.getText();
        try {
            VatDung vatDungData = new VatDung();
            String arr[] = {"Mã vật dụng", "Tên vật dụng", "Số lượng", "Tình trạng", "Mã phòng"};
            List <VatDung> listVatDung = vatDungData.timVatDung(tenVatDung);
            DefaultTableModel dtm = new DefaultTableModel(arr,0);
            tbThongTinVatDung.removeAll();
            tbThongTinVatDung.setModel(dtm);
            
            for (VatDung vd : listVatDung) {
                dtm.addRow(new Object[]{
                    vd.getMaVatDung(), vd.getTenVatDung()
                   ,vd.getSoLuong(), vd.getTinhTrang()
                   ,vd.getMaPhong()
                });
            }
            
            dtm.fireTableDataChanged();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ThongTinCacPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        try {
            // TODO add your handling code here:
            timVatDung();
        } catch (SQLException ex) {
            Logger.getLogger(ThongTinVatDungPhongPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        try {
            // TODO add your handling code here:
            txtTimKiem.setText("");
            loadData();
        } catch (SQLException ex) {
            Logger.getLogger(ThongTinVatDungPhongPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtMaVatDung.setEnabled(true);
        txtMaVatDung.setText("");
        
        txtTimKiem.setText("");
        txtTenVatDung.setText("");
        txtSoLuong.setText("");
        
        txtMaPhong.setEnabled(true);
        txtMaPhong.setText("");
    }//GEN-LAST:event_btnLamMoiActionPerformed

    
    /**
     * Hàm biểu diễn thông tin lên text field
     * @param row 
     */
    private void displayToTextField(int row){
        txtMaVatDung.setEnabled(false);
        txtMaVatDung.setText((String) tbThongTinVatDung.getModel().getValueAt(row, 0));
        
        txtTenVatDung.setText((String) tbThongTinVatDung.getModel().getValueAt(row, 1));
        
        txtSoLuong.setText((String) tbThongTinVatDung.getModel().getValueAt(row, 2));
        
        String tinhTrang = (String) tbThongTinVatDung.getModel().getValueAt(row, 3);
        
        switch (tinhTrang) {
            case "Tốt" -> cbbTinhTrang.setSelectedIndex(0);
            case "Hư hỏng" -> cbbTinhTrang.setSelectedIndex(1);
            default -> cbbTinhTrang.setSelectedIndex(2);
        }
        
        txtMaPhong.setEnabled(false);
        txtMaPhong.setText((String) tbThongTinVatDung.getModel().getValueAt(row, 4));
    }
    
    
    private void tbThongTinVatDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbThongTinVatDungMouseClicked
        // TODO add your handling code here:
        
        int row = tbThongTinVatDung.getSelectedRow();
        
        displayToTextField(row);
    }//GEN-LAST:event_tbThongTinVatDungMouseClicked

    private void btnSuaThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaThongTinActionPerformed
        // TODO add your handling code here:
        
        String maVatDung = txtMaVatDung.getText();

        String tenVatDung = txtTenVatDung.getText();
        
        String soLuong = txtSoLuong.getText();
        
        String tinhTrang = (String) cbbTinhTrang.getSelectedItem();
        
        VatDung vd = new VatDung();
        
        int index = 0;
        
        try {
            index = vd.SuaThongTinVatDung(maVatDung, tenVatDung,Integer.parseInt(soLuong), tinhTrang);
            
            if(index > 0){
                JOptionPane.showMessageDialog(this, "Sửa thông tin thành công");
                loadData();
            }
            else
                JOptionPane.showMessageDialog(this, "Sửa thông tin thất bại");
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
        
    }//GEN-LAST:event_btnSuaThongTinActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        
        String maVatDung = txtMaVatDung.getText();
        
        String tenVatDung = txtTenVatDung.getText();
        
        String soLuong = txtSoLuong.getText();
        
        String maPhong = txtMaPhong.getText();
        
        String trangThai = (String)cbbTinhTrang.getSelectedItem();
        
        VatDung vd = new VatDung();
        
        int index = 0;
        
        
        try {
            
            if(maVatDung.equals("") || tenVatDung.equals("") 
                    || soLuong.equals("") || maPhong.equals(""))
                    JOptionPane.showMessageDialog(this, "Thông tin chưa đầy đủ"
                        , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE); 
            else
                index = vd.ThemVatDung(maVatDung, tenVatDung, Integer.parseInt(soLuong), trangThai, maPhong);
            
            if(index > 0){
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                loadData();
            }
            else
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            
            
        } catch (HeadlessException | SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Mã vật dụng đã tồn tại");
        }
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaVatDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaVatDungActionPerformed
        // TODO add your handling code here:
        int ret = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa","Xóa vật dụng",JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION){
            String maXoa = txtMaVatDung.getText();
        
            String maPhong = txtMaPhong.getText();

            int index = 0;
            VatDung vd = new VatDung();

            try {
                if(maXoa.equals("") || maPhong.equals(""))
                    JOptionPane.showMessageDialog(this, "Không để trống các mã"
                        , "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
                else
                    index = vd.XoaVatDung(maXoa, maPhong);

                if(index > 0){
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    loadData();
                }
                else
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");

            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(ThongTinVatDungPhongPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
    }//GEN-LAST:event_btnXoaVatDungActionPerformed


    /**
     * Hàm load thông tin lên table
     * @throws SQLException 
     */
    public void loadData() throws SQLException{
        try {
            VatDung vatDungData = new VatDung();
            String arr[] = {"Mã vật dụng", "Tên vật dụng", "Số lượng", "Tình trạng", "Mã phòng"};
            List <VatDung> listVatDung = vatDungData.getFullData();
            DefaultTableModel dtm = new DefaultTableModel(arr,0);
            tbThongTinVatDung.removeAll();
            tbThongTinVatDung.setModel(dtm);
            
            for (VatDung vd : listVatDung) {
                dtm.addRow(new Object[]{
                    vd.getMaVatDung(), vd.getTenVatDung()
                   ,vd.getSoLuong(), vd.getTinhTrang()
                   ,vd.getMaPhong()
                });
            }
            
            dtm.fireTableDataChanged();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ThongTinCacPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSuaThongTin;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoaVatDung;
    private javax.swing.JComboBox<String> cbbTinhTrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbThongTinVatDung;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtMaVatDung;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenVatDung;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
