/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author DeskTop_Linh04
 */
public class HomePageCus extends javax.swing.JFrame {

    /**
     * Creates new form HomePageCus
     */
    public HomePageCus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        DatphongjLabel = new javax.swing.JLabel();
        datDichVujLabel = new javax.swing.JLabel();
        ThanhtoanjLabel = new javax.swing.JLabel();
        ThongTinjLabel = new javax.swing.JLabel();
        dangKyjLabel = new javax.swing.JLabel();
        dangNhapjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        DatphongjLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DatphongjLabel.setText("Đặt phòng");
        DatphongjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DatphongjLabelMouseClicked(evt);
            }
        });

        datDichVujLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        datDichVujLabel.setText("Đặt dịch vụ");
        datDichVujLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datDichVujLabelMouseClicked(evt);
            }
        });

        ThanhtoanjLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ThanhtoanjLabel.setText("Thanh toán");
        ThanhtoanjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThanhtoanjLabelMouseClicked(evt);
            }
        });

        ThongTinjLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ThongTinjLabel.setText("Thông Tin");
        ThongTinjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThongTinjLabelMouseClicked(evt);
            }
        });

        dangKyjLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dangKyjLabel.setText("Đăng ký");
        dangKyjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dangKyjLabelMouseClicked(evt);
            }
        });

        dangNhapjLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dangNhapjLabel.setText("Đăng nhập");
        dangNhapjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dangNhapjLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(DatphongjLabel)
                .addGap(18, 18, 18)
                .addComponent(datDichVujLabel)
                .addGap(18, 18, 18)
                .addComponent(ThanhtoanjLabel)
                .addGap(18, 18, 18)
                .addComponent(ThongTinjLabel)
                .addGap(18, 18, 18)
                .addComponent(dangKyjLabel)
                .addGap(31, 31, 31)
                .addComponent(dangNhapjLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DatphongjLabel)
                    .addComponent(datDichVujLabel)
                    .addComponent(ThanhtoanjLabel)
                    .addComponent(ThongTinjLabel)
                    .addComponent(dangKyjLabel)
                    .addComponent(dangNhapjLabel))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThongTinjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongTinjLabelMouseClicked
        // TODO add your handling code here:
       
        JOptionPane.showMessageDialog(this,"Bạn chưa đăng nhập","lỗi",JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_ThongTinjLabelMouseClicked

    private void DatphongjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatphongjLabelMouseClicked
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this,"Bạn chưa đăng nhập","lỗi",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_DatphongjLabelMouseClicked

    private void datDichVujLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datDichVujLabelMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Bạn chưa đăng nhập","lỗi",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_datDichVujLabelMouseClicked

    private void dangKyjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangKyjLabelMouseClicked
        // TODO add your handling code here:
        signUp signup = new signUp();
        signup.setVisible(true); 
        this.dispose();// xóa trang trước
    }//GEN-LAST:event_dangKyjLabelMouseClicked

    private void dangNhapjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangNhapjLabelMouseClicked
        // TODO add your handling code here:
        login dangnhap = new login();
        dangnhap.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_dangNhapjLabelMouseClicked

    private void ThanhtoanjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThanhtoanjLabelMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Bạn chưa đăng nhập","lỗi",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_ThanhtoanjLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageCus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageCus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageCus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageCus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageCus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DatphongjLabel;
    private javax.swing.JLabel ThanhtoanjLabel;
    private javax.swing.JLabel ThongTinjLabel;
    private javax.swing.JLabel dangKyjLabel;
    private javax.swing.JLabel dangNhapjLabel;
    private javax.swing.JLabel datDichVujLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
