/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author DeskTop_Linh04
 */
public class HomePageCusAfter extends javax.swing.JFrame {

    /**
     * Creates new form HomePageCusAfter
     */
    public HomePageCusAfter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        DatPhongjLabel = new javax.swing.JLabel();
        DatDichVujLabel = new javax.swing.JLabel();
        ThanhtoanjLabel = new javax.swing.JLabel();
        ThongTinjLabel = new javax.swing.JLabel();
        DangXuatjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));

        DatPhongjLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DatPhongjLabel.setText("Đặt phòng");
        DatPhongjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DatPhongjLabelMouseClicked(evt);
            }
        });

        DatDichVujLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DatDichVujLabel.setText("Đặt dịch vụ");
        DatDichVujLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DatDichVujLabelMouseClicked(evt);
            }
        });

        ThanhtoanjLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ThanhtoanjLabel.setText("Thanh toán");
        ThanhtoanjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThanhtoanjLabelMouseClicked(evt);
            }
        });

        ThongTinjLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ThongTinjLabel.setText("Thông tin");
        ThongTinjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThongTinjLabelMouseClicked(evt);
            }
        });

        DangXuatjLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DangXuatjLabel.setText("Đăng Xuất");
        DangXuatjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DangXuatjLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(DatPhongjLabel)
                .addGap(18, 18, 18)
                .addComponent(DatDichVujLabel)
                .addGap(18, 18, 18)
                .addComponent(ThanhtoanjLabel)
                .addGap(18, 18, 18)
                .addComponent(ThongTinjLabel)
                .addGap(18, 18, 18)
                .addComponent(DangXuatjLabel)
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DatPhongjLabel)
                    .addComponent(DatDichVujLabel)
                    .addComponent(ThanhtoanjLabel)
                    .addComponent(ThongTinjLabel)
                    .addComponent(DangXuatjLabel))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThongTinjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongTinjLabelMouseClicked
        // TODO add your handling code here:
        inforUser infouser = new inforUser();
        infouser.setVisible(true);
    }//GEN-LAST:event_ThongTinjLabelMouseClicked

    private void DatPhongjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatPhongjLabelMouseClicked
        // TODO add your handling code here:
        orderRoom orderroom = new orderRoom();
        orderroom.setVisible(true);
    }//GEN-LAST:event_DatPhongjLabelMouseClicked

    private void DatDichVujLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatDichVujLabelMouseClicked
        // TODO add your handling code here:
        orderService orderser = new orderService ();
        orderser.setVisible(true);
    }//GEN-LAST:event_DatDichVujLabelMouseClicked

    private void ThanhtoanjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThanhtoanjLabelMouseClicked
        // TODO add your handling code here:
        payMent payment = new payMent();
        payment.setVisible(true); 
    }//GEN-LAST:event_ThanhtoanjLabelMouseClicked

    private void DangXuatjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangXuatjLabelMouseClicked
        // TODO add your handling code here:
        HomePageCus  homepage = new HomePageCus();
        homepage.setVisible(true); 
    }//GEN-LAST:event_DangXuatjLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageCusAfter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageCusAfter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageCusAfter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageCusAfter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageCusAfter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DangXuatjLabel;
    private javax.swing.JLabel DatDichVujLabel;
    private javax.swing.JLabel DatPhongjLabel;
    private javax.swing.JLabel ThanhtoanjLabel;
    private javax.swing.JLabel ThongTinjLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
